# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:

    - &OrdererOrg
     
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/bc4scm.de/msp

    - &IBO
      
        Name: IBOMSP
        ID: IBOMSP
        MSPDir: crypto-config/peerOrganizations/ibo.bc4scm.de/msp
        AnchorPeers:
            - Host: peer0.ibo.bc4scm.de
              Port: 7051

Application: &ApplicationDefaults

    Organizations:

Orderer: &OrdererDefaults
   
    OrdererType: solo

    Addresses:
        - orderer.bc4scm.de:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

Profiles:

    OneOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *IBO
    OneOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *IBO

